voca:
  gems:
    decidim-decidim_awesome:
      version: '>= 0.10'
    decidim-term_customizer:
      git: 'https://github.com/mainio/decidim-module-term_customizer'
      branch: 'release/0.27-stable'
    decidim-only_forms:
      git: "https://git.octree.ch/decidim/decidim-module-only_forms"
      branch: "release/0.27-stable"
